name: DevOpsLab_1

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      
      - name: Install Requirements
        run: pip install -r requirements.txt
        
      - name: Build App
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          standalone: true
          onefile: true
      
      - name: Upload Exe
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: build/main.exe
